### PR TITLE
logo draft

### PR DESCRIPTION
**Pull request by ihlec**
first draft of the Decentralized-Open-Science-Logo

### CODE REVIEW

**Comment by ihlec** [comment]
logo

**Comment by physikerwelt** [comment]
maybe we can use the openacess color and the color for the OSI logo or the uni wuppertal

**Comment by dennis-tra** [comment]
image

**Comment by physikerwelt** [comment]
> image

I would vote for this logo. However, we can clarify this on Friday.

**Review by dennis-tra — APPROVED** [review]

**Review by physikerwelt — APPROVED** [review]

**Pull request merged**
